os: osx
language: objective-c
osx_image: xcode11.3

branches:
  only:
    - master

env:
  global:
    - THEOS=theos

before_install:
  - brew install ldid
  - git clone --recursive https://github.com/Shade-Zepheri/theos.git $THEOS

script:
  - make package